---
# Observability stack secrets. Consumed by Grafana (OIDC SSO credentials).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: observability-secrets
  namespace: observability
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${cluster_secret_store}
  target:
    name: observability-secrets
    creationPolicy: Owner
  data:
    - secretKey: grafana-oidc-client-id
      remoteRef:
        key: Grafana SSO
        property: oidc-client-id
    - secretKey: grafana-oidc-client-secret
      remoteRef:
        key: Grafana SSO
        property: oidc-client-secret
