---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - grafana-storage.yaml
  - externalsecret.yaml
  - alertmanager-config.yaml
  - grafana-rbac.yaml
  - release.yaml
