---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vpa-system
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - release.yaml

components:
  - ../../../components/netpol-baseline
