---
apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/managed-by: flux
    # ClusterSecretStore opt-in label (configs/cluster-secret-store.yaml).
    ${cluster_node_label_domain}/cluster-secrets: "true"
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
