---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry-cache

resources:
  - namespace.yaml
  - externalsecret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - vpa.yaml

components:
  - ../../components/netpol-baseline
  - ../../components/netpol-egress-dns
