"""Unit tests for scripts/check-flux-version-pin.py.

Each test builds a throwaway repository root, points the gate at it with
`--root`, and asserts the exit code.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

GATE = Path(__file__).resolve().parent / "check-flux-version-pin.py"

CI = 'cluster-verify:\n  script:\n    - |\n      FLUX_VERSION="{version}"\n'
CM = "apiVersion: v1\ndata:\n  flux_version: {version}\nkind: ConfigMap\n"
GOTK = (
    "---\n"
    "# This manifest was generated by flux. DO NOT EDIT.\n"
    "# Flux Version: v{version}\n"
    "# Components: {components}\n"
)
CONTROLLERS = "source-controller,kustomize-controller,helm-controller,notification-controller"


def _tree(tmp_path: Path, pin="2.9.0", cm="2.9.0", gotk=None, components=CONTROLLERS) -> Path:
    (tmp_path / ".gitlab-ci.yml").write_text(CI.format(version=pin))
    cm_path = tmp_path / "kubernetes/infrastructure/sources"
    cm_path.mkdir(parents=True)
    (cm_path / "versions-configmap.yaml").write_text(CM.format(version=cm))
    if gotk is not None:
        gotk_dir = tmp_path / "kubernetes/clusters/example/flux-system"
        gotk_dir.mkdir(parents=True)
        (gotk_dir / "gotk-components.yaml").write_text(
            GOTK.format(version=gotk, components=components)
        )
    return tmp_path


def _run(root: Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(GATE), "--root", str(root), *extra],
        capture_output=True,
        text=True,
        check=False,
    )


def test_three_agreeing_pins_pass(tmp_path):
    res = _run(_tree(tmp_path, gotk="2.9.0"))
    assert res.returncode == 0, res.stdout + res.stderr


def test_a_pre_bootstrap_repository_checks_the_two_files_it_has(tmp_path):
    # gotk-components.yaml is written by `flux bootstrap`, so its absence is the
    # normal state of a freshly generated cluster, not a failure.
    res = _run(_tree(tmp_path))
    assert res.returncode == 0, res.stdout + res.stderr
    assert "checked the pin against the ConfigMap only" in res.stdout


def test_a_configmap_that_drifted_from_the_pin_fails(tmp_path):
    res = _run(_tree(tmp_path, pin="2.9.0", cm="2.8.0", gotk="2.9.0"))
    assert res.returncode == 1
    assert "versions-configmap.yaml (2.8.0) disagree" in res.stdout


def test_a_pre_bootstrap_repository_still_fails_on_configmap_drift(tmp_path):
    res = _run(_tree(tmp_path, pin="2.9.0", cm="2.8.0"))
    assert res.returncode == 1


def test_gotk_components_generated_by_another_cli_fails(tmp_path):
    # The mutation this gate exists for: the CLI that ran `flux bootstrap` was
    # not the CLI the pipeline installs, so the committed control plane is
    # a version nobody reviewed.
    res = _run(_tree(tmp_path, gotk="2.7.0"))
    assert res.returncode == 1
    assert "disagree" in res.stdout


def test_a_changed_controller_set_fails(tmp_path):
    res = _run(_tree(tmp_path, gotk="2.9.0", components="source-controller,kustomize-controller"))
    assert res.returncode == 1
    assert "not " + CONTROLLERS in res.stdout


EXTRA = CONTROLLERS + ",image-reflector-controller,image-automation-controller"


def test_an_extra_components_bootstrap_fails_until_the_set_is_declared(tmp_path):
    res = _run(_tree(tmp_path, gotk="2.9.0", components=EXTRA))
    assert res.returncode == 1
    assert "--components" in res.stdout


def test_an_extra_components_bootstrap_passes_with_the_matching_flag(tmp_path):
    res = _run(_tree(tmp_path, gotk="2.9.0", components=EXTRA), "--components", EXTRA)
    assert res.returncode == 0, res.stdout + res.stderr


def test_a_declared_set_the_manifest_does_not_match_still_fails(tmp_path):
    res = _run(_tree(tmp_path, gotk="2.9.0", components=CONTROLLERS), "--components", EXTRA)
    assert res.returncode == 1
    assert "not " + EXTRA in res.stdout


def test_a_second_ci_pin_that_disagrees_fails(tmp_path):
    # The mutation first-match-only hides: a second job installs another CLI and
    # every pin after the first goes unchecked.
    root = _tree(tmp_path, gotk="2.9.0")
    (root / ".gitlab-ci.yml").write_text(
        CI.format(version="2.9.0") + CI.format(version="2.7.0")
    )
    res = _run(root)
    assert res.returncode == 1
    assert "pins several Flux versions" in res.stdout


def test_two_agreeing_ci_pins_pass(tmp_path):
    root = _tree(tmp_path, gotk="2.9.0")
    (root / ".gitlab-ci.yml").write_text(
        CI.format(version="2.9.0") + CI.format(version="2.9.0")
    )
    res = _run(root)
    assert res.returncode == 0, res.stdout + res.stderr


def test_a_second_configmap_key_that_disagrees_fails(tmp_path):
    root = _tree(tmp_path, gotk="2.9.0")
    (root / "kubernetes/infrastructure/sources/versions-configmap.yaml").write_text(
        "apiVersion: v1\ndata:\n  flux_version: 2.9.0\n  k3s_version: v1.36.4+k3s1\n"
        "---\napiVersion: v1\ndata:\n  flux_version: 2.7.0\n"
    )
    res = _run(root)
    assert res.returncode == 1
    assert "several flux_version values" in res.stdout


def test_a_second_gotk_header_that_disagrees_fails(tmp_path):
    """A re-export appended rather than replaced leaves two headers, and only the
    second describes the control plane that actually shipped."""
    root = _tree(tmp_path, gotk="2.9.0")
    gotk = root / "kubernetes/clusters/example/flux-system/gotk-components.yaml"
    gotk.write_text(gotk.read_text() + GOTK.format(version="2.7.0", components=CONTROLLERS))
    res = _run(root)
    assert res.returncode == 1
    assert "(2.7.0) disagree" in res.stdout


def test_a_missing_pin_reports_that_it_inspected_nothing(tmp_path):
    root = _tree(tmp_path, gotk="2.9.0")
    (root / ".gitlab-ci.yml").write_text("cluster-verify:\n  script:\n    - flux --version\n")
    res = _run(root)
    assert res.returncode == 2
    assert "no FLUX_VERSION" in res.stderr


def test_a_missing_configmap_key_reports_that_it_inspected_nothing(tmp_path):
    root = _tree(tmp_path, gotk="2.9.0")
    (root / "kubernetes/infrastructure/sources/versions-configmap.yaml").write_text(
        "apiVersion: v1\ndata:\n  k3s_version: v1.36.4+k3s1\nkind: ConfigMap\n"
    )
    res = _run(root)
    assert res.returncode == 2
    assert "no flux_version key" in res.stderr


def test_a_non_utf8_pipeline_reports_that_it_inspected_nothing(tmp_path):
    """A file the gate cannot decode is an operator error, not a clean pin."""
    root = _tree(tmp_path, gotk="2.9.0")
    (root / ".gitlab-ci.yml").write_bytes(b'FLUX_VERSION: "\xff\xfe"\n')
    res = _run(root)
    assert res.returncode == 2
    assert "unreadable" in res.stderr
