---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-operator-crds
  labels:
    app.kubernetes.io/name: prometheus-operator-crds
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/managed-by: flux
